import { v4 as uuidv4 } from "uuid"

export const PLAYERS = [
    {
        id: 0,
        first_name: 'Azeez',
        last_name: 'Al-Shaair',
        team: 'Tennessee Titans',
        position: 'LB',
        number: '2',
        age: '26',
        height: '6020', 
        weight: '228',
        college: 'Florida Atlantic',
        years_experience: '8',
        imageURL: 'https://static.clubs.nfl.com/image/private/t_landscape_tablet_2x/f_auto/titans/pra8kwqr2uvrrnhteisu.jpg'
    }, 
    {
        id: 1,
        first_name: "Denico",
        last_name: 'Autry',
        team: 'Tennessee Titans',
        position: 'DE',
        number: '96',
        age:  '33',
        height: '6050', 
        weight: '285',
        college: 'Mississippi State',
        years_experience: '11',
        imageURL: 'https://static.clubs.nfl.com/image/private/t_landscape_tablet_2x/f_auto/titans/sohoywlfn3bodqhl4tdk.jpg',
    },
    {
        id: 2,
        first_name: 'Tre',
        last_name: 'Avery',
        team: 'Tennessee Titans',
        position: 'CB',
        number: '23',
        age:  '27',
        height: '5110', 
        weight: '181',
        college: 'Rutgers',
        years_experience: '3',
        imageURL: 'https://static.clubs.nfl.com/image/private/t_landscape_tablet_2x/f_auto/titans/wxds7exgbfxkg8oaj24j.jpg',
    },
    // {
    //     id: uuidv4(),
    //     first_name: ,
    //     last_name: ,
    //     team: 'Tennessee Titans',
    //     position: ,
    //     number: ,
    //     age:  ,
    //     height: , 
    //     weight: ,
    //     college: ,
    //     imageURL: ,
    // },
    // {
    //     id: uuidv4(),
    //     first_name: ,
    //     last_name: ,
    //     team: 'Tennessee Titans',
    //     position: ,
    //     number: ,
    //     age:  ,
    //     height: , 
    //     weight: ,
    //     college: ,
    //     imageURL: ,
    // },
    // {
    //     id: uuidv4(),
    //     first_name: ,
    //     last_name: ,
    //     team: 'Tennessee Titans',
    //     position: ,
    //     number: ,
    //     age:  ,
    //     height: , 
    //     weight: ,
    //     college: ,
    //     imageURL: ,
    // },
    // {
    //     id: uuidv4(),
    //     first_name: ,
    //     last_name: ,
    //     team: 'Tennessee Titans',
    //     position: ,
    //     number: ,
    //     age:  ,
    //     height: , 
    //     weight: ,
    //     college: ,
    //     imageURL: ,
    // },
    // {
    //     id: uuidv4(),
    //     first_name: ,
    //     last_name: ,
    //     team: 'Tennessee Titans',
    //     position: ,
    //     number: ,
    //     age:  ,
    //     height: , 
    //     weight: ,
    //     college: ,
    //     imageURL: ,
    // }


]